### PR TITLE
no

### PR DESCRIPTION
**Pull request by baumanisking**
oh my god this ui is so ugly hope you delete this repo now

sorry, i was just joking.

### CODE REVIEW

**Comment by inari-codes** [comment]
if you don't like this then can't you just leave this alone?

**Comment by anotherperson69** [comment]
hei idiot @saimoomedits what @baumanisking said is right, your ui is fucking suck

**Comment by anotherperson69** [comment]
and wtf you doing idiot, did u have changed the PR title and his comment? are you ashamed to admit this dotfiles have a bad looking? lmfao 👅

**Comment by yxqsnz** [comment]
lmao

**Comment by yxqsnz** [comment]
stop rxyhn

**Comment by ahmed12345678910111213141516** [comment]
this dotfile looks great
don't listen to them

**Pull request closed without merging**
